# here I am creating some seed data to work with and test association

#Here i am creating 3 users
abhiman = User.create(name: "Abhiman", email: "abhi@abhiman.com", password: "abhiman")
sujit = User.create(name: "Sujit", email: "sujit@myrachana.com", password: "sujit")
siya = User.create(name: "Siya", email: "siya@siya.com", password: "siya")

#and 4 book_entries
abhiman.book_entries.create(name: "The Origin", author: "Dan Brown", notes: "Sometimes, all you have to do is shift your perspective to see someone else's truth.",status: false)
sujit.book_entries.create(name: "The Krishna Key", author: "Ashwin Sanghi", notes: "Modern scientists now believe that there are seven broad forms of energy—mechanical, heat, chemical, radiant, electrical, sound, and nuclear. It is my reasoned guess that the ancient yogis knew this. They also knew that each of these could be broken into seven constituent elements! It’s impossible to understand how they knew this, but they did. Even their most important and exalted river—the Sarasvati—was part of the Saptasindhu, the seven rivers. Vedic knowledge was derived from the Saptarishi—the seven sages. Even Dwarka was the embodiment of Saptadweep—the seven islands.",status: true)
siya.book_entries.create(name: "Ram: The Scion of Ikshvaku Book 1 ", author: "Amish", notes: "Swagruhe Pujyate Murkhaha; Swagraame Pujyate Prabhuhu Swadeshe Pujyate Raja; Vidvaansarvatra Pujyate. A fool is worshipped in his home. A chief is worshipped in his village. A king is worshipped in his kingdom. A knowledgeable person is worshipped everywhere.",status: true)
siya.book_entries.create(name: "Sita: The Scion of Ikshvaku Book 2 ", author: "Amish", notes: "You know, Guru Vashishta had said to me, when I was a child, that compassion is sometimes an overrated virtue. He told me the story of the butterfly emerging from the hard pupa. Its life begins as an “ugly” caterpillar. When the time is right, it forms a pupa and retreats behind its hard walls. Within its shell, it transforms into a butterfly, unseen, unheard. When ready, it uses its tiny, sharp claws at the base of its forewings to crack a small opening in the hard, protective outer shell. It squeezes through this tiny opening and struggles to make its way out. This is a difficult, painful and prolonged process. Misguided compassion may make us want to enlarge the hole in the pupa, imagining that it would ease the butterfly’s task. But that struggle is necessary; as the butterfly squeezes its body out of the tiny hole, it secretes fluids within its swollen body. This fluid goes to its wings, strengthening them; once they’ve emerged, as the fluid dries, the delicate creatures are able to take flight. Making the hole bigger to “help” the butterfly and ease its struggle will only debilitate it. Without the struggle, its wings would never gain strength. It would never fly.",status: true)
